### PR TITLE
Fix the heartbeat issue #40

### PR DESCRIPTION
**Pull request by deepsleep**
1. Fix issue #40 found in both StompClientConnectionImpl and DefaultStompHandler.

2. Add unit test testAsymmetricHeartbeatTime to StompClientImplTest.

### CODE REVIEW

**Comment by cescoffier** [comment]
@deepsleep did you sign the Eclipse CLA?

**Comment by deepsleep** [comment]
@cescoffier  Sorry that I am not sure about that, since it's my first PR in Github. And sure I would like to sign the Eclipse CLA.

**Comment by cescoffier** [comment]
@deepsleep you just have to create an account and sign the CLA on https://accounts.eclipse.org/user/login?destination=user/eca. 

The value behind this extra step is to be sure that the contribution is "cleared" in term of IP. You sign the CLA only once for all your contribution to Eclipse projects.

**Comment by deepsleep** [comment]
Thanks @cescoffier. I have signed the Eclipse CLA.  And my email address of Eclipse account is jfcheng87@gmail.com . Thanks again. :)

**Pull request merged**
